### ISSUE TITLE
Class web does not exist

### ISSUE THREAD

**Issue by austinkregel** [nickdekruijk/larapages#1]
So I just installed this package and it never mentions the "web" middleware... Shouldn't it be the 'auth' middleware?

**Comment by nickdekruijk** [comment]
What version of Laravel are you using? I'm on 5.2 and 'web' works just fine. 5.1 should use 'auth' probably

**Comment by austinkregel** [comment]
I am on 5.1, I don't want to upgrade to 5.2 just yet. I'm thinking about moving up to 5.2 sometime, just need to upgrade like 4-5 projects and I don't have the time for it right now.

**Comment by nickdekruijk** [comment]
Maybe I should add $version=='5.1'?'auth':'web' or something? Is there a global variable that has the laravel version?

**Comment by austinkregel** [comment]
My thought in this case would be to use your own middleware, or to force the move to 5.2 and update your dependencies accordingly. There's probably another option, if you look hard enough.

**Comment by austinkregel** [comment]
Maybe make a fork for 5.1 and one for 5.2 but forks are a pain in the butt  to deal with (I personally don't like modifying forks)

**Comment by nickdekruijk** [comment]
I've made some changes that also solves this issue: LaraPages doesn't use the out of the box Authentication Middleware but it's own Middleware.
