### ISSUE TITLE
Class 'App\Page' not found

### ISSUE THREAD

**Issue by austinkregel** [nickdekruijk/larapages#2]
Will you please move your Page model into your package. I'll try to deduce what I need to make the proper model for my implementation of the app :)

**Comment by nickdekruijk** [comment]
I've added my sample Page model and migration to the sample folder. It's from a project I did with working CMS but before I decided to turn the CMS into a package so it may need some changes.
Is there a better method for adding a model and migration to a laravel package? I'm new to package creation so any tips are welcome.

**Comment by austinkregel** [comment]
The way I usually build my packages, is that I think of them as it's own project. I give the package it's own resource, config, Http, etc... folders. That way it's similar the default Laravel setup, and it's easy to understand.

So I typically have my packages set up something like this, it all depends on what your package is designed for.

```
src/
    |- MyPackageName/
        |- Http/
            |- Controllers
            |- Middleware
            |- routes.php
        |- Models/
            |- MyModel.php
        |- Commands/
    |- config/
    |- resources/
        |- views/
            |- base.blade.php
```

**Comment by nickdekruijk** [comment]
And how do you use a model from a package? Page extends \NickDeKruijk\LaraPageModel?

**Comment by austinkregel** [comment]
I have my models extend Eloquent. That way Taylor can change the location and namespacing for Model without breaking all my apps :P
